# Site settings
title: "CV Harris Design, LLC"
email: cvharris1014@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Development & Design Contracting. I enjoy working on side
  projects that interest me. Love listening to passionate
  people share their ideas with me, and especially love helping them!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cvharris.com" # the base hostname & protocol for your site
twitter_username: chesterbelloc14
github_username:  cvharris

# Build settings
markdown: kramdown

# Gem Plugins
gems: []
